name: Release Charts

on:
  push:
    branches:
      - "main"
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout whole repo
        uses: actions/checkout@v2
        with:
          repository: 'datashim-io/datashim'
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Search for latest tag
        id: search_latest_tag
        run: |
          LATEST_TAG=$(git tag --list --sort=creatordate | egrep '^[0-9]+\.[0-9]+\.[0-9]+' | tail -1)
          echo "Latest tag is $LATEST_TAG"
          helm repo add datashim https://swissdatasciencecenter.github.io/datashim-charts/ || true
          helm repo update || true
          HELM_SEARCH_RESULT=$(helm search repo datashim --version $LATEST_TAG --output json || true)
          echo "::set-output name=helm_search_result::$HELM_SEARCH_RESULT"
          echo "::set-output name=latest_tag::$LATEST_TAG"
      
      - name: Checkout tag
        if: ${{ steps.search_latest_tag.outputs.helm_search_result != '[]' }}
        run: |
          echo "Checking out tag ${{ steps.search_latest_tag.outputs.latest_tag }}"
          git checkout ${{ steps.search_latest_tag.outputs.latest_tag }}
      
      - name: Package chart
        if: ${{ steps.search_latest_tag.outputs.helm_search_result != '[]' }}
        run: |
          helm package ./chart -u -d ./.helm-deploy/
      
      - name: Publish chart
        if: ${{ steps.search_latest_tag.outputs.helm_search_result != '[]' }}
        uses: docker://quay.io/helmpack/chart-releaser:v1.2.1
        run: |
          ls -la
          cr version